services:
  # 백엔드 서비스 (먼저 배포)
  - type: web
    name: snu-plp-hub-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
    autoDeploy: true
    healthCheckPath: /api/recommendations

  # 프론트엔드 서비스
  - type: web
    name: snu-political-leaders-hub-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      # SPA 라우팅을 위한 설정
      - path: /*
        name: Cache-Control
        value: no-cache
      # CORS 헤더 추가
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    routes:
      # API 요청은 백엔드로 프록시
      - type: redirect
        source: /api/*
        destination: https://snu-plp-hub-backend.onrender.com/api/*
        status: 307
      # SPA를 위한 모든 경로를 index.html로 리다이렉트
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://snu-plp-hub-backend.onrender.com/api
      - key: NODE_ENV
        value: production
    autoDeploy: true

