services:
  # 백엔드 서비스 (Node.js API 서버) - 먼저 배포
  - type: web
    name: plp-api-server
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
    autoDeploy: true

  # 프론트엔드 서비스 (정적 사이트)
  - type: web
    name: plp-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      # SPA 라우팅을 위한 설정
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      # SPA를 위한 모든 경로를 index.html로 리다이렉트
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://plp-api-server.onrender.com/api
      - key: NODE_ENV
        value: production
    autoDeploy: true

